version: '3'

services:
  keycloak_imported:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_imported
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpwd
    volumes:
      - ./data:/opt/keycloak/data/import
    command: ['start-dev', '--import-realm']
